#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 31 09:07:40 2025

@author: u0890475
"""

from all_functions import*
import math

gc_file_path = '/home/u0890475/Documents/Analysis_Codes_Matt/gc_time.csv'
gc_df = get_gc_data(gc_file_path)
timesteps = gc_df["Timestep"]
gc = gc_df["g_isosrf"]

"""
fig = mono_plot(timesteps, gc,"timestep (s)","g_c","gc vs timesteps")
plt.show()
"""

flame1 = build_flame(300, 101325, 0.375)
sd,alpha = get_flame_info(flame1)
dt = [ math.sqrt(alpha/x) for x in gc]
dc = [sd/x for x in gc]